import dotenv from "dotenv";
dotenv.config();
const {
  CLIENTID,
  GUILDID,
  DISCORDBOTTOKEN,
  IMGAPI,
  NEWUSERSCHANNELID,
  NEWUSERSNOTABLECHANNELID,
  ZEROSHARECHANNELID,
  ZEROSHARE10CHANNELID,
  ZEROSHARENOTABLECHANNELID,
  ZEROSHARE50CHANNELID,
  BASERPC,
  FTAUTHTOKEN,
  FTUSERID,
} = process.env;

if (
  !CLIENTID ||
  !GUILDID ||
  !DISCORDBOTTOKEN ||
  !IMGAPI ||
  !NEWUSERSCHANNELID ||
  !NEWUSERSNOTABLECHANNELID ||
  !ZEROSHARECHANNELID ||
  !ZEROSHARE10CHANNELID ||
  !ZEROSHARE50CHANNELID ||
  !ZEROSHARENOTABLECHANNELID ||
  !BASERPC ||
  !FTAUTHTOKEN ||
  !FTUSERID
) {
  throw new Error("Missing .env vars");
}

const config: Record<string, string> = {
  CLIENTID,
  GUILDID,
  DISCORDBOTTOKEN,
  IMGAPI,
  NEWUSERSCHANNELID,
  NEWUSERSNOTABLECHANNELID,
  ZEROSHARECHANNELID,
  ZEROSHARE10CHANNELID,
  ZEROSHARE50CHANNELID,
  ZEROSHARENOTABLECHANNELID,
  BASERPC,
  FTAUTHTOKEN,
  FTUSERID,
};

export default config;
